name: Daily Stock Report

on:
  schedule:
    - cron: '30 22 * * *' # 매일 한국 시간 약 오전 7시 30분 실행
  workflow_dispatch: # 직접 실행하고 싶을 때 사용하는 버튼 추가

jobs:
  run-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python main.py
